require('dotenv').config();
const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
const authRoutes = require('./routes/authRoutes');
const groceryRoutes = require('./routes/groceryRoutes');
const app = express();
connectDB();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/grocery', groceryRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`[SYSTEM RUNTIME] Server engine actively pooling over port node: ${PORT}`));
